export const categories = [
  { id: 'all', label: 'Minden' }, { id: 'braai', label: 'Braai & szószok' },
  { id: 'spices', label: 'Fűszerek' }, { id: 'chutney', label: 'Chutney & relish' },
  { id: 'tea', label: 'Tea & rusks' }, { id: 'snacks', label: 'Snack & édesség' },
  { id: 'pantry', label: 'Kamra alapok' }
];

export const products = [
  {
    id: 'peri-peri-hot', slug: 'nandos-peri-peri-hot', name: "Nando's Peri-Peri Hot", subtitle: 'Csípős szósz · 250 g', price: 3490, category: 'braai', categoryName: 'Braai szószok', badge: 'BRAAI PICK', visual: 'bottle', tone: 'red', story: 'Tüzes, citrusos peri-peri karakter grillezett húsokhoz, zöldségekhez és marinádokhoz.',
    details: { summary: 'Karakteresen csípős, citrusos peri-peri szósz grillezett ételekhez, pácokhoz és mártogatósokhoz.', what: 'A peri-peri chilire épülő, savas-fűszeres szósztípus. Kész asztali szószként, pácként vagy más mártások ízesítőjeként is használható.', background: 'A peri-peri ízvilág Dél-Afrikában a portugál és délkelet-afrikai kulináris hatások találkozásához kapcsolódik. A braai, vagyis a dél-afrikai szabadtéri grillezés gyakori kísérője.', flavour: 'Erős chili, friss citrusosság, fokhagymás-fűszeres alap és hosszan megmaradó csípősség.', uses: ['grillezett csirke és húsok', 'sült vagy grillezett zöldségek', 'marinádok, majonézek és mártogatósok'], serving: ['Keverd majonézbe sült burgonya mellé.', 'Ecseteld grillezett csirkére a sütés végén.', 'Adj néhány cseppet egy zöldséges tálhoz.'], suits: 'A csípős, savas ízek kedvelőinek és braai-hangulatú grillezésekhez.', storage: 'Felbontás előtt hűvös, száraz helyen tartsd. Felbontás után kövesd a csomagolás tárolási útmutatóját.', info: '250 g-os csípős szósz. Az összetevőkért, allergénekért és minőségmegőrzésért mindig a csomagolás az irányadó.', faq: [['Mennyire csípős?', 'Határozottan csípős változat; kis mennyiséggel érdemes kezdeni.'], ['Használható pácként?', 'Igen, önmagában vagy olajjal és citruslével keverve.'], ['Csak húshoz illik?', 'Nem. Zöldségekhez, tofuhoz és mártogatósokhoz is jól használható.']] }
  },
  {
    id: 'mrs-balls-original', slug: 'mrs-balls-original-chutney', name: "Mrs Ball's Original Chutney", subtitle: 'Gyümölcsös chutney', price: 4290, category: 'chutney', categoryName: 'Chutney és relish', badge: 'CAPE CLASSIC', visual: 'jar', tone: 'fig', story: 'Édeskés-savanykás dél-afrikai klasszikus, curryhez, sajtokhoz és szendvicsekhez.',
    details: { summary: 'Sűrű, gyümölcsös, édes-savanyú chutney currykhez, sajttálakhoz, húsokhoz és szendvicsekhez.', what: 'A chutney gyümölcsből, ecetes-savanyú és fűszeres elemekből készülő sűrű ízesítő. Nem lekvár: az édességet savasság és fűszeresség egyensúlyozza.', background: 'A chutney Dél-Afrika sokrétegű konyhájának ismert asztali kísérője. Gyakran kerül curry, bobotie, grillezett hús vagy hideg falatok mellé.', flavour: 'Gyümölcsös édesség, kerek savasság, enyhe fűszeresség és telt, lekváros állag.', uses: ['curry és bobotie mellé', 'sajtokhoz és hidegtálakhoz', 'szendvicsekhez, burgerekhez és grillezett húsokhoz'], serving: ['Tálald érlelt cheddar és keksz mellé.', 'Adj egy kanállal meleg curryhez.', 'Használd burgerben relish helyett.'], suits: 'Az édes-savanyú ízek kedvelőinek, sajtrajongóknak és dél-afrikai receptekkel ismerkedőknek.', storage: 'Hűvös, száraz helyen tárold; felbontás után a címkén jelzett módon, jellemzően hűtve.', info: 'Gyümölcsös chutney. A pontos kiszerelést, összetevőket, allergéneket és minőségmegőrzést a csomagolás jelzi.', faq: [['Miben más, mint a relish?', 'Általában gyümölcsösebb, édesebb és sűrűbb állagú.'], ['Csípős?', 'Az eredeti változat inkább fűszeres-édes, nem erősen csípős.'], ['Meleg ételbe is tehető?', 'Igen, tálaláskor vagy szószok ízesítésére is használható.']] }
  },
  {
    id: 'rooibos-original', slug: 'carmien-rooibos-original', name: 'Carmién Rooibos Original', subtitle: 'Koffeinmentes tea', price: 2890, category: 'tea', categoryName: 'Rooibos tea és rusks', badge: 'CEDERBERG', visual: 'box', tone: 'rooibos', story: 'Természetesen koffeinmentes rooibos, lágy, mézes-fás karakterrel.',
    details: { summary: 'Természetesen koffeinmentes, lágy rooibos tea mézes, fás és enyhén karamelles jegyekkel.', what: 'A rooibos az Aspalathus linearis dél-afrikai növény leveleiből készülő vörös főzet. Nem teacserje, ezért természeténél fogva koffeinmentes.', background: 'A rooibos Dél-Afrika Cederberg térségéhez kötődik, ahol a növény természetes élőhelye található. Melegen és jegesen is a dél-afrikai teakultúra jellegzetes itala.', flavour: 'Lágy, alacsony csersavérzetű, mézes-fás és enyhén karamelles karakter.', uses: ['önmagában meleg teaként', 'tejjel vagy növényi itallal', 'jegestea, latte és desszertek alapjaként'], serving: ['Áztasd forró vízben 5–7 percig.', 'Tálald citrommal és kevés mézzel.', 'Hűtsd le, majd add narancshoz és jéghez.'], suits: 'Koffeint kerülőknek, esti teázáshoz és lágyabb főzetet keresőknek.', storage: 'Száraz, hűvös helyen, fénytől és erős illatoktól védve tárold.', info: 'Eredeti rooibos tea. A filterek számáért, elkészítésért és allergén információért a csomagolás az irányadó.', faq: [['Van benne koffein?', 'A tiszta rooibos természeténél fogva koffeinmentes.'], ['Tejjel is iható?', 'Igen, lágy íze jól működik tejjel vagy növényi itallal.'], ['Meddig kell áztatni?', 'Általában 5–7 perc ad telt, sima főzetet.']] }
  },
  {
    id: 'braai-rub', slug: 'cape-braai-rub', name: 'Cape Braai Rub', subtitle: 'Fűszerkeverék · 120 g', price: 2590, category: 'spices', categoryName: 'Dél-afrikai fűszerek', badge: 'BRAAI APPROVED', visual: 'tin', tone: 'olive', story: 'Füstös, korianderes és paprikás fűszerkeverék húsokhoz, gombához és grillzöldségekhez.',
    details: { summary: 'Füstös, paprikás és korianderes száraz fűszerkeverék húsokhoz, gombához és grillzöldségekhez.', what: 'A rub száraz fűszerkeverék, amelyet sütés előtt az alapanyag felületére dörzsölnek. Kérget, aromát és színt ad nedves pác nélkül.', background: 'A braai Dél-Afrikában nem csupán grillezési mód, hanem közösségi étkezési alkalom. A fűszeres kéreg és a faszenes íz ennek jellegzetes része.', flavour: 'Füstös paprika, földes koriander, sós-fűszeres alap és meleg aromák.', uses: ['marha-, sertés- és csirkehúshoz', 'gombához, kukoricához és grillzöldségekhez', 'sült burgonyához vagy fűszeres vajhoz'], serving: ['Olajozd be vékonyan, majd dörzsöld rá.', 'Pihentesd sütés előtt 20–30 percig.', 'Keverd vajba grillezett kukoricához.'], suits: 'Grillezőknek, intenzív fűszeres ízek kedvelőinek és gyors pácoláshoz.', storage: 'Jól lezárva, száraz, hűvös helyen, gőztől és napfénytől védve tartsd.', info: '120 g-os fűszerkeverék. Só- és allergéntartalomért, valamint összetevőkért ellenőrizd a címkét.', faq: [['Kell mellé só?', 'Ellenőrizd a keverék sótartalmát, és csak ezután sózz külön.'], ['Mennyi kell belőle?', 'Kezdésként vékony, egyenletes réteg javasolt.'], ['Sütőben is használható?', 'Igen, serpenyőben, sütőben és grillen is működik.']] }
  },
  {
    id: 'chakalaka-relish', slug: 'chakalaka-relish', name: 'Chakalaka Relish', subtitle: 'Fűszeres zöldség relish', price: 3290, category: 'chutney', categoryName: 'Chutney és relish', badge: 'SPICY', visual: 'jar', tone: 'orange', story: 'Paprikás-paradicsomos, fűszeres relish braai mellé, rizshez vagy friss kenyérhez.',
    details: { summary: 'Paprikás-paradicsomos, zöldséges és fűszeres relish, amely köretként és ízesítőként is használható.', what: 'A chakalaka főtt, fűszeres zöldségkeverék. Receptje változó, de gyakori eleme a paradicsom, paprika, hagyma és a meleg fűszerezés.', background: 'A chakalaka Dél-Afrikában népszerű kísérőétel, amelyet gyakran braai, pap, kenyér vagy tartalmas egytálételek mellé kínálnak.', flavour: 'Paradicsomos alap, édes paprika, hagymás zamat és közepesen csípős, meleg fűszeresség.', uses: ['braai és sült húsok mellé', 'pap, rizs vagy bab ízesítésére', 'pirítósra, wrapbe vagy melegszendvicsbe'], serving: ['Tálald szobahőmérsékleten grillezett ételhez.', 'Melegítsd össze főtt babbal.', 'Kanalazd pirítósra lágy tojás alá.'], suits: 'Zöldséges, csípős köreteket keresőknek és közös étkezésekhez.', storage: 'Bontatlanul hűvös, száraz helyen; felbontás után hűtve és a címke szerint fogyaszd.', info: 'Fűszeres zöldség-relish. Az összetevők, allergének, tömeg és csípősség tekintetében a címke az irányadó.', faq: [['Hidegen vagy melegen jobb?', 'Mindkét módon fogyasztható; köretként gyakran szobahőmérsékleten kínálják.'], ['Nagyon csípős?', 'Fűszeres termék, de az intenzitást a címke és az egyéni érzékenység határozza meg.'], ['Mi az a pap?', 'Dél-Afrikában elterjedt, kukoricaőrleményből főzött köret.']] }
  },
  {
    id: 'rooibos-rusks', slug: 'rooibos-buttermilk-rusks', name: 'Rooibos Buttermilk Rusks', subtitle: 'Ropogós sütemény · 300 g', price: 3790, category: 'tea', categoryName: 'Rooibos tea és rusks', badge: 'TEA TIME', visual: 'bag', tone: 'sand', story: 'Dél-afrikai rusk rooibos mellé: ropogós, vajas, mártogatásra készült.',
    details: { summary: 'Keményre szárított, írós jellegű dél-afrikai sütemény rooibos ízvilággal, meleg italba mártogatáshoz.', what: 'A dél-afrikai rusk kétszer sütött vagy lassan szárított, ropogós sütemény. Száraz állaga tudatos: meleg italba mártva válik puhává.', background: 'A rusks a dél-afrikai reggelik és teázások ismerős kísérői. Praktikus, hosszan eltartható süteményként váltak a mindennapi kamra részévé.', flavour: 'Vajas, enyhén karamelles, gabonás íz, finom rooibos-jegyekkel és száraz, roppanós állaggal.', uses: ['rooibos vagy fekete tea mellé', 'kávéba mártogatva', 'reggelihez és utazós snackként'], serving: ['Mártsd forró rooibosba néhány másodpercre.', 'Tálald hétvégi reggeli részeként.', 'Párosítsd mézes vagy vaníliás italokkal.'], suits: 'Ropogós kekszek kedvelőinek, teázóknak és dél-afrikai reggeli élményt keresőknek.', storage: 'Felbontás után légmentesen zárva, száraz helyen tartsd, hogy ropogós maradjon.', info: '300 g-os ropogós sütemény. Tej-, glutén- és egyéb allergénekért ellenőrizd a csomagolást.', faq: [['Miért ilyen kemény?', 'A ruskot szándékosan szárítják; meleg italba mártogatva fogyasztják.'], ['Csak rooibosszal ehető?', 'Nem, kávéval, fekete teával vagy kakaóval is jól működik.'], ['Hogyan marad ropogós?', 'Felbontás után légmentesen zárt dobozban tárold.']] }
  },
  {
    id: 'peppermint-crisp', slug: 'peppermint-crisp-treat', name: 'Peppermint Crisp Treat', subtitle: 'Mentás csokoládés snack', price: 1790, category: 'snacks', categoryName: 'Dél-afrikai snackek és édességek', badge: 'SWEET PICK', visual: 'bar', tone: 'guava', story: 'Mentás-csokoládés dél-afrikai kedvenc, gyors desszerthez vagy ajándékcsomagba.',
    details: { summary: 'Ropogós mentás és csokoládés édesség, amely önmagában snack, de hűtött desszertekhez is használható.', what: 'Mentás-csokoládés szelet, amelyben a hűs menta, az édes csokoládé és a roppanós textúra adja a kontrasztot.', background: 'A mentás csokoládé Dél-Afrikában kultikus desszertíz. Rétegezett hűtött desszertekben gyakran találkozik karamellel, tejszínes elemekkel és keksszel.', flavour: 'Hűs borsmenta, édes csokoládé és könnyű, roppanós cukorkás textúra.', uses: ['önálló édességként', 'hűtött, rétegezett desszertek tetején', 'fagylalthoz, brownie-hoz vagy ajándékcsomagba'], serving: ['Törd apróra vaníliafagylalt fölé.', 'Rétegezd keksszel és karamelles krémmel.', 'Hűtsd be tálalás előtt az extra roppanásért.'], suits: 'Mentás csokoládé rajongóinak, dél-afrikai édességekkel ismerkedőknek és játékos desszertekhez.', storage: 'Hűvös, száraz helyen, közvetlen napfénytől és hőtől védve tárold.', info: 'Mentás csokoládés snack. A pontos tömeg, összetevők, allergének és minőségmegőrzés a csomagoláson található.', faq: [['Önmagában is fogyasztható?', 'Igen, közvetlenül a csomagolásból is snackként fogyasztható.'], ['Milyen desszerthez illik?', 'Fagylalthoz, brownie-hoz és karamelles, hűtött réteges desszertekhez.'], ['Erős a menta íze?', 'A menta határozott, hűs kontrasztot ad az édes csokoládéhoz.']] }
  },
  {
    id: 'maize-meal', slug: 'south-african-maize-meal', name: 'South African Maize Meal', subtitle: 'Kukoricadara · 1 kg', price: 2190, category: 'pantry', categoryName: 'Dél-afrikai kamra alapok', badge: 'PANTRY', visual: 'bag', tone: 'mango', story: 'Pap és más klasszikus köretek alapja, semleges ízzel és sokoldalú felhasználással.',
    details: { summary: 'Finomra őrölt kukoricaalap a dél-afrikai pap elkészítéséhez: semleges ízű, laktató és sokoldalú.', what: 'A maize meal szárított kukoricából őrölt alapanyag. Vízben főzve az aránytól függően lágy kását vagy formázható, sűrű köretet ad.', background: 'A pap Dél-Afrika széles körben fogyasztott alapkörete. Braai, paradicsomos-hagymás szósz, chakalaka, húsos ragu vagy zöldséges fogás mellett is megjelenik.', flavour: 'Enyhén kukoricás, tiszta és semleges; elsősorban a mellé tálalt szószokat és fűszereket emeli ki.', uses: ['sűrű pap köretként', 'lágy reggeli kásaként', 'szaftos húsos, babos vagy zöldséges ételek mellé'], serving: ['Főzd sűrűre, és tálald chakalakával.', 'Kínáld braai hús és paradicsomos mártás mellé.', 'Készíts lágyabb kását tejjel vagy növényi itallal.'], suits: 'Dél-afrikai alapételeket felfedezőknek és semleges, jól variálható kamra-alapot keresőknek.', storage: 'Száraz, hűvös helyen, jól záródó edényben, nedvességtől védve tárold.', info: '1 kg kukoricaőrlemény. A szemcseméret, főzési idő és allergén információk tekintetében a csomagolás az irányadó.', faq: [['Mi a pap?', 'Kukoricaőrleményből és vízből főzött, sűrű dél-afrikai köret.'], ['Polenta helyett használható?', 'Hasonló alapanyag, de eltérhet; kövesd a csomagolás útmutatóját.'], ['Édesen is elkészíthető?', 'Igen, lágyabb kásaként tejjel és enyhe édesítéssel is tálalható.']] }
  }
];

export function getProductBySlug(slug) { return products.find((item) => item.slug === slug); }
export function formatPrice(value) { return new Intl.NumberFormat('hu-HU').format(value) + ' Ft'; }
