export const categories = [
  { id:'all', label:'Minden termék' },
  { id:'braai', label:'Braai & szószok', visualLabel:['BRAAI','& SZÓSZOK'], image:'/products/peri-hot.webp', tone:'red' },
  { id:'spices', label:'Fűszerek & rubok', visualLabel:['FŰSZEREK','& RUBOK'], image:'/products/rajah-curry.webp', tone:'olive' },
  { id:'pate', label:'Pástétomok', visualLabel:['PÁSTÉTOM','& ÍNYENCSÉG'], image:'/products/pate-springbok.webp', tone:'fig' },
  { id:'tea', label:'Tea & rusks', visualLabel:['TEA','& RUSKS'], image:'/products/rusks.webp', tone:'orange' },
  { id:'snacks', label:'Snack & ital', visualLabel:['SNACK','& ITAL'], image:'/products/peanut.webp', tone:'guava' },
  { id:'pantry', label:'Kamra alapok', visualLabel:['KAMRA','& ALAPOK'], image:'/products/evoo.webp', tone:'sand' }
];

const contexts = {
  braai:'A braai Dél-Afrikában egyszerre szabadtéri sütési mód és közösségi alkalom. A peri-peri savassággal, chilivel és fűszerekkel élénkíti a grillételeket.',
  spices:'A dél-afrikai kamrában az őrölt fűszerek és száraz rubok a curryktől a braai fogásokig sokféle ételben megjelennek.',
  pate:'A vadhúsos pástétom felfedező jellegű hidegtál-elemként illeszkedik a dél-afrikai gasztronómiai válogatásokba. A pontos eredetet a csomagolás közli.',
  tea:'A rooibos Dél-Afrika Cederberg térségéhez kötődik, a rusk pedig a reggelik és teázások jellegzetes, meleg italba mártogatható kísérője.',
  snacks:'A dél-afrikai hétköznapi kamra édes és sós klasszikusai reggelihez, italhoz vagy egyszerű snackhez is jól használhatók.',
  pantry:'A jól megválasztott kamra-alapok sütéshez, grillezéshez és gyors hétköznapi fogásokhoz adnak biztos kiindulópontot.'
};

const rows = [
  ["peri-hot","nandos-peri-peri-hot","Nando's Peri-Peri Hot","Csípős szósz · 250 g",3490,"braai","Braai & szószok","HOT PICK","red","peri-hot.png","Határozottan csípős, citrusos peri-peri szósz grillezett ételekhez, pácokhoz és mártogatósokhoz.","Kész, chili-alapú asztali szósz, amely pácként vagy mártások ízesítőjeként is használható.","Erős chili, friss savasság és fokhagymás-fűszeres karakter.","A markáns, csípős ízek kedvelőinek.","250 g-os, Hot jelölésű szósz.",['grillezett csirke és húsok','sült zöldségek','majonéz és pác'],['Keverd majonézbe.','Ecseteld a húsra sütés végén.','Adj néhány cseppet zöldségekhez.']],
  ["peri-lemon","nandos-peri-peri-lemon-herb","Nando's Peri-Peri Lemon & Herb","Citromos-fűszeres szósz · 250 g",null,"braai","Braai & szószok","MILD PICK","orange","peri-lemon.png","Lágyabb, citromos-fűszeres peri-peri szósz könnyű grillételekhez és mártogatáshoz.","A peri-peri szósz enyhébb, citrusos változata, kész szószként és pácként is adagolható.","Citromos frissesség, zöldfűszeres jegyek és visszafogott chili.","Azoknak, akik peri-peri karaktert keresnek erős csípősség nélkül.","250 g-os, Lemon & Herb jelölésű szósz.",['grillezett csirke és hal','joghurtos mártás','zöldségek és szendvicsek'],['Keverd joghurtba.','Használd csirke pácolásához.','Locsold sült zöldségekre.']],
  ["rajah-curry","rajah-curry-powder-selection","Rajah Curry Powder Selection","Curry válogatás · 5 × 50 g",null,"spices","Fűszerek & rubok","SPICE ROUTE","olive","rajah-curry.png","Ötféle curry fűszerkeverékből álló válogatás többféle intenzitás kipróbálásához.","Előre összeállított őrölt keverékek curryhez, rizses fogásokhoz és ragukhoz.","Meleg, földes és aromás curryjegyek; a karakter keverékenként eltér.","Kísérletező szakácsoknak és curryprofilok összehasonlításához.","A fotón öt, egyenként 50 g-os csomag látható.",['húsos vagy zöldséges curry','lencse és rizs','fűszeres pác'],['Pirítsd röviden hagymával.','Kezdd kis mennyiséggel.','Keverd joghurtos pácba.']],
  ["braai-seasoning","ina-paarmans-braai-grill-seasoning","Ina Paarman's Braai & Grill Seasoning","Braai és grill fűszer",null,"spices","Fűszerek & rubok","BRAAI READY","red","braai-seasoning.png","Sokoldalú száraz grillfűszer húsok, gomba, kukorica és sült zöldségek ízesítésére.","Sütés előtt az alapanyagra szórható vagy olajos pácba keverhető száraz fűszer.","Sós, fűszeres, grillhez hangolt aromák; a pontos összetételt a címke jelzi.","Gyors, kiszámítható grillízt keresőknek.","A pontos nettó tömeg a csomagoláson ellenőrizhető.",['húsok','gomba és kukorica','burgonya és fűszervaj'],['Szórd olajozott felületre.','Pihentesd húsz percig.','Keverd fűszervajba.']],
  ["peri-rub","cape-herb-spice-portuguese-peri-peri-rub","Cape Herb & Spice Portuguese Peri Peri Rub","Peri-peri rub · 100 g",2590,"spices","Fűszerek & rubok","PERI RUB","rooibos","rub-periperi.png","Paprikás, csípős száraz peri-peri rub húsokhoz és grillzöldségekhez.","Száraz keverék, amely kérget, aromát és színt ad nedves pác nélkül.","Meleg paprika, chili és enyhén füstös fűszeresség.","A peri-peri karaktert száraz fűszerezésben keresőknek.","100 g-os Portuguese Peri Peri Rub.",['csirke és garnéla','karfiol és burgonya','olajos pác'],['Dörzsöld vékonyan az alapanyagra.','Keverd olajjal.','Szórd sült burgonyára.']],
  ["springbok-pate","springbok-pate-mild-herb","Springbok Pâté Mild Herb","Springbok pástétom",null,"pate","Pástétomok & ínyencségek","GAME TASTE","fig","pate-springbok.png","Enyhén zöldfűszeres springbok pástétom pirítóshoz, kekszhez és hidegtálhoz.","Kenhető, fűszerezett vadhúsos pástétom; a pontos hústartalmat a címke közli.","Sós, telt, húsos karakter enyhe zöldfűszeres kísérettel.","Vadhúsos ízekkel ismerkedőknek és különleges hidegtálakhoz.","Mild Herb jelölés; a pontos tömeg a címkén található.",['pirítós és keksz','sajtos hidegtál','ajándékkosár'],['Tálald nem túl hidegen.','Adj mellé savanyúságot.','Kínáld vékony pirítóssal.']],
  ["zebra-pate","zebra-pate-rosemary-wine","Zebra Pâté Rosemary & Wine","Zebra pástétom",null,"pate","Pástétomok & ínyencségek","BOLD PAIRING","fig","pate-zebra.png","Rozmaringos-boros jellegű zebra pástétom karakteres előételhez vagy kóstolótálhoz.","Kenhető vadhúsos pástétom boros és rozmaringos profillal; az összetevőarányokat a címke közli.","Telt, húsos alap, rozmaring és kerek, boros fűszeresség.","Karakteres vadhúsos ízeket kereső, kíváncsi kóstolóknak.","Rosemary & Wine jelölés; a pontos tömeg a címkén található.",['kovászos pirítós','savanyított zöldség','kóstolótál'],['Kínáld ropogós kenyérrel.','Adj mellé savanyúságot.','Párosítsd chutney-val.']],
  ["rooibos","freshpak-pure-rooibos-80","Freshpak Pure Rooibos","Rooibos · 80 filter",2890,"tea","Tea & rusks","ROOIBOS","rooibos","rooibos.png","Természetesen koffeinmentes, lágy rooibos tea mézes, fás és enyhén karamelles jegyekkel.","Az Aspalathus linearis dél-afrikai növényből készülő vörös főzet, nem hagyományos tealevél.","Lágy, alacsony csersavérzetű, mézes-fás és karamelles.","Koffeint kerülőknek és esti teázáshoz.","80 tagless filtert tartalmazó Pure Rooibos csomag.",['meleg tea','rooibos latte','jegestea'],['Áztasd 5–7 percig.','Tálald citrommal.','Hűtsd le naranccsal.']],
  ["rusks","ouma-sliced-buttermilk-rusks","Ouma Sliced Buttermilk Rusks","Írós rusk · 8 szelet",3790,"tea","Tea & rusks","TEA TIME","sand","rusks.png","Keményre szárított írós rusk, amelyet hagyományosan meleg italba mártogatva fogyasztanak.","Kétszer sütött vagy szárított ropogós sütemény, amely mártogatva válik puhává.","Vajas, enyhén karamelles, gabonás íz és roppanós állag.","Teázóknak és mártogatható süteményt kedvelőknek.","8 külön csomagolt buttermilk rusk.",['rooibos','kávé','reggeli snack'],['Mártsd rooibosba.','Tálald reggelihez.','Párosítsd kakaóval.']],
  ["milo","nestle-milo-malt-energy-drink","Nestlé Milo Malt Energy Drink","Malátás italpor · 150 g",null,"snacks","Snack & ital","MALT CLASSIC","olive","milo.png","Kakaós-malátás italpor meleg vagy hideg tejhez, gabonás csokoládéízzel.","Tejben elkeverhető instant italpor; az elkészítési arányt a csomagolás jelzi.","Édes kakaó, pirított maláta és krémes, gabonás érzet.","Kakaós-malátás ízek kedvelőinek és gyors italhoz.","150 g-os Milo Malt Energy Drink italpor.",['meleg vagy hideg tej','turmix','zabkása'],['Keverd tejhez.','Adj banános turmixhoz.','Szórd zabkására.']],
  ["peanut","black-cat-smooth-peanut-butter","Black Cat Smooth Peanut Butter","Krémes mogyoróvaj",null,"snacks","Snack & ital","PANTRY ICON","guava","peanut.png","Sima állagú mogyoróvaj pirítóshoz, zabkásához, turmixhoz és sós szószokhoz.","Finomra őrölt földimogyoró-alapú krém; a hozzáadott összetevőket a címke részletezi.","Pörkölt mogyoró, sós-édes egyensúly és krémes textúra.","Krémes mogyoróvajat keresőknek; földimogyoró-allergiával nem fogyasztható.","Smooth jelölés; a pontos tömeg a címkén található.",['pirítós és zabkása','turmix','mogyorós öntet'],['Kend pirítósra banánnal.','Turmixold kakaóval.','Keverd chilis öntetbe.']],
  ["biltong","kalahari-biltong-powder-shaker","Kalahari Biltong Powder Shaker","Biltong por shakerben",null,"snacks","Snack & ital","SAVOURY","rooibos","biltong.png","Sós, húsos jellegű biltong por könnyen adagolható shakerben, ételek befejező ízesítésére.","Finomra őrölt biltong-alapú szórható ízesítő; hústartalmát és allergénjeit a címke adja meg.","Koncentrált, sós, szárított húsos és fűszeres karakter.","Umami, sós és húsos ízek kedvelőinek.","Shaker kiszerelés; a pontos tömeg a címkén található.",['tojás és burgonya','leves és tészta','popcorn'],['Szórd rá tálalás előtt.','Adj rántottához.','Ízesíts sült burgonyát.']],
  ["evoo","willow-creek-estate-blend-extra-virgin-olive-oil","Willow Creek Estate Blend Extra Virgin Olive Oil","Extra szűz olívaolaj · 750 ml",null,"pantry","Kamra alapok","ESTATE BLEND","sand","evoo.png","Közepes intenzitású extra szűz olívaolaj salátához, kenyérhez és kész ételek befejezéséhez.","Mechanikai eljárással nyert extra szűz olívaolaj, Estate Blend és Medium jelöléssel.","Közepes intenzitású, gyümölcsös-zöld karakter; szüretenként eltérhet.","Sokoldalú, közepes karakterű olívaolajat keresőknek.","750 ml-es, Medium jelölésű Estate Blend.",['saláta','kenyérmártogatás','grillezett zöldség'],['Öntsd friss kenyér mellé.','Keverd citromos öntetbe.','Locsold grillzöldségre.']]
];

export const products = rows.map(([id,slug,name,subtitle,price,category,categoryName,badge,tone,file,summary,what,flavour,suits,info,uses,serving]) => ({
  id,slug,name,subtitle,price,category,categoryName,badge,tone,image:`/products/${file.replace('.png','.webp')}`,editorialImage:`/editorial/${category}.jpg`,visual:'box',story:summary,
  details:{summary,what,background:contexts[category],flavour,uses,serving,suits,
    storage:category==='tea'?'Száraz, hűvös helyen, fénytől és erős illatoktól védve tárold.':category==='pate'?'A címkén jelzett hőmérsékleten tárold; felbontás után hűtsd és a gyártó útmutatója szerint fogyaszd.':'Hűvös, száraz, közvetlen napfénytől védett helyen tárold; felbontás után kövesd a címkét.',
    info:`${info} Az összetevőkért, allergénekért, tápértékért és minőségmegőrzésért mindig a csomagolás az irányadó.`,
    faq:[['Hogyan érdemes először megkóstolni?',serving[0]],['Mivel párosítható?',`Jó kiindulópont: ${uses.slice(0,2).join(' és ')}.`],['Hol találom az allergénadatokat?','Mindig az aktuális termékcsomagoláson; fogyasztás előtt ellenőrizd a címkét.']]
  }
}));

export function getProductBySlug(slug){return products.find((item)=>item.slug===slug);}
export function formatPrice(value){return value==null?'Ár hamarosan':`${new Intl.NumberFormat('hu-HU').format(value)} Ft`;}
