import { DEFAULT_UI_COPY } from '@/lib/site-config';

function merge(base, override) {
  if (Array.isArray(base)) return Array.isArray(override) ? override : base;
  if (!base || typeof base !== 'object') return override === undefined ? base : override;
  const out = { ...base };
  for (const [key, value] of Object.entries(override || {})) out[key] = key in base ? merge(base[key], value) : value;
  return out;
}

export const STOREFRONT_COPY_EXTENSION = {
  nav: { profile: 'Profil', menu: 'Menü', closeMenu: 'Menü bezárása' },
  accessibility: { home: 'deli.africa kezdőlap', close: 'Bezárás', cartDecrease: 'Mennyiség csökkentése', cartIncrease: 'Mennyiség növelése' },
  shop: { productUnavailable: 'Ár hamarosan', categoryCountTemplate: 'VÁLOGATÁS · {count} TERMÉK' },
  productPage: {
    navShop:'Shop',navStory:'Történet',home:'Kezdőlap',back:'Vissza a shophoz',unavailable:'Hamarosan rendelhető',introEyebrow:'ELSŐ KÓSTOLÁS ELŐTT',introTitle:'Minden, ami a jó választáshoz kell.',packageTitle:'Mi van a csomagban?',backgroundTitle:'Miért dél-afrikai kedvenc?',flavourTitle:'Milyen ízre számíts?',suitsTitle:'Neked való, ha…',usageEyebrow:'FELHASZNÁLÁS',pairingTitle:'Mivel párosítsd?',servingEyebrow:'TÁLALÁS',servingTitle:'Három gyors ötlet',storageEyebrow:'JÓ, HA TUDOD',storageTitle:'Így marad a legjobb.',faqEyebrow:'GYAKORI KÉRDÉSEK',faqTitleTemplate:'Kérdések a {name} termékről',relatedEyebrow:'HA EZ TETSZIK',relatedTitleTemplate:'Kóstolj még innen: {category}',relatedLink:'Megnézem közelebbről →',addToCart:'Kosárba',addedToCart:'Kosárba téve ✓',editorialAltTemplate:'{name} tálalási ötlet'
  },
  categories: {
    braai:{label:'Braai & szószok',visualLine1:'BRAAI',visualLine2:'& SZÓSZOK',title:'Braai szószok dél-afrikai grillezéshez',lead:'Peri-peri szószok és karakteres ízek húsokhoz, zöldségekhez, pácokhoz és mártogatósokhoz.',context:'A braai több egyszerű grillezésnél: közös étkezés, tűz és együtt töltött idő. Ebben a válogatásban olyan szószokat találsz, amelyek gyorsan adnak savasságot, chilit és fűszeres mélységet a kész fogásokhoz.',tip:'Kezdd kevés szósszal, majd kóstolás után rétegezd tovább az ízt.'},
    spices:{label:'Fűszerek & rubok',visualLine1:'FŰSZEREK',visualLine2:'& RUBOK',title:'Fűszerek és rubok a hétköznapi főzéstől a braaiig',lead:'Száraz keverékek curryhez, grillezéshez, sült zöldségekhez és gyors pácokhoz.',context:'Az őrölt currykeverékek és rubok egyszerű módon adnak összetett, meleg vagy csípős karaktert. Használhatod őket közvetlenül az alapanyagon, olajjal elkeverve vagy a főzés elején hagymával röviden megpirítva.',tip:'Első használatkor adagolj visszafogottan; a fűszer intenzitása főzés közben erősödhet.'},
    pate:{label:'Pástétomok',visualLine1:'PÁSTÉTOM',visualLine2:'& ÍNYENCSÉG',title:'Dél-afrikai vadhúsos pástétomok',lead:'Karakteres, kenhető különlegességek pirítóshoz, hidegtálhoz és kíváncsi kóstolóknak.',context:'A vadhúsos pástétomokat érdemes egyszerű kísérőkkel tálalni, hogy a húsos és fűszeres karakter érvényesüljön. Ropogós kenyér, savanyúság vagy enyhén édes chutney jó kiindulópont.',tip:'Tálalás előtt röviden hagyd temperálódni, és mindig ellenőrizd a csomagolás tárolási útmutatóját.'},
    tea:{label:'Tea & rusks',visualLine1:'TEA',visualLine2:'& RUSKS',title:'Rooibos tea és dél-afrikai rusks',lead:'Koffeinmentes rooibos és mártogatásra kész, ropogós rusk a lassabb reggelekhez.',context:'A rooibos a dél-afrikai Cederberg térségéhez kötődik, lágy, mézes-fás karaktere pedig önmagában, tejjel vagy jegesen is működik. A rusk keményre szárított sütemény, amelyet hagyományosan meleg italba mártva fogyasztanak.',tip:'A rooibost 5–7 percig áztasd; a ruskot csak röviden mártsd az italba.'},
    snacks:{label:'Snack & ital',visualLine1:'SNACK',visualLine2:'& ITAL',title:'Dél-afrikai snackek és italok',lead:'Ismerős formák különleges dél-afrikai karakterrel, reggelitől az esti nassolásig.',context:'A kakaós-malátás italpor, a mogyoróvaj és a sós biltong ízesítő különböző alkalmakra való, de közös bennük a könnyű használhatóság. A termékoldalakon konkrét párosításokat és első kóstolási ötleteket találsz.',tip:'Válassz az alkalom szerint: italhoz Milo, krémes reggelihez mogyoróvaj, sós befejezéshez biltong por.'},
    pantry:{label:'Kamra alapok',visualLine1:'KAMRA',visualLine2:'& ALAPOK',title:'Kamra-alapok dél-afrikai ihletéssel',lead:'Sokoldalú alapanyagok salátához, kenyérhez, grillezéshez és gyors hétköznapi fogásokhoz.',context:'Egy jó kamra-alap nem uralja az ételt, hanem összeköti az ízeket. A válogatás termékei többféle fogásban használhatók, a legegyszerűbb tálalástól a braai köretekig.',tip:'Tárold a csomagolás szerint, hőtől és közvetlen napfénytől védve.'}
  },
  categoryPage:{navShop:'Shop',navStory:'Történet',allProducts:'Összes termék',home:'Kezdőlap',whyEyebrow:'MIÉRT ÉRDEMES MEGKÓSTOLNI?',whyTitle:'Ízek, amelyekhez rögtön van ötleted.',productsEyebrow:'A KATEGÓRIA TERMÉKEI',productsTitle:'Válassz kedved szerint.',unavailable:'Hamarosan',detailsLink:'Részletek és tálalási ötletek →',heroAltTemplate:'{category} dél-afrikai tálalási környezetben'},
  profile:{loading:'Profil betöltése…',loadError:'Nem sikerült betölteni a profilt.',saveError:'A mentés sikertelen.',saveSuccess:'Profiladatok mentve. A mentett címek a következő rendelésnél is használhatók.',backToShop:'Vissza a shophoz',logout:'Kijelentkezés',eyebrow:'SAJÁT FIÓK',title:'Profil',customerFallback:'Vásárló',metaTitle:'Profil | deli.africa',metaDescription:'Mentett szállítási és számlázási adatok, valamint rendelési előzmények.',statsOrders:'Rendelések',statsSpent:'Összes vásárlás',statsLastOrder:'Utolsó rendelés',contactEyebrow:'KAPCSOLAT',contactTitle:'Alapadatok',name:'Név',email:'E-mail',phone:'Telefonszám',phonePlaceholder:'+36…',shippingEyebrow:'SZÁLLÍTÁS',shippingTitle:'Mentett szállítási cím',shippingHelp:'Ezt az adatot használhatod a következő rendeléseknél.',recipientName:'Címzett neve',country:'Ország',postalCode:'Irányítószám',city:'Város',address:'Cím',addressPlaceholder:'Utca, házszám',address2:'Cím 2',address2Placeholder:'Emelet, ajtó, épület – opcionális',deliveryNote:'Szállítási megjegyzés',billingEyebrow:'SZÁMLÁZÁS',billingTitle:'Mentett számlázási adatok',copyShipping:'Szállítási cím másolása',billingName:'Számlázási név',companyName:'Cégnév',taxNumber:'Adószám',billingAddress:'Számlázási cím',billingAddress2:'Számlázási cím 2',saving:'MENTÉS…',save:'ADATOK MENTÉSE',historyEyebrow:'ELŐZMÉNYEK',historyTitle:'Rendeléseim',noOrders:'Még nincs rendelésed.',paymentLabel:'Fizetés',deliveryLabel:'Szállítás',tracking:'Csomag követése'},
  authError:{eyebrow:'SSO HIBA',title:'A bejelentkezés nem sikerült.',body:'A munkamenet lejárhatott, vagy az alkalmazás-hozzáférés nincs még jóváhagyva.',retry:'Újrapróbálom',back:'Vissza a webshophoz'},
  legalPage:{metaTitleTemplate:'{title} · {company}'},
  social:{instagram:'Instagram',x:'X',facebook:'Facebook'},
  orderStatus:{payment:{not_started:'Nincs elindítva',pending:'Fizetés folyamatban',paid:'Fizetve',failed:'Sikertelen fizetés',refunded:'Visszatérítve'},delivery:{not_started:'Nincs elindítva',label_created:'Címke elkészült',in_transit:'Szállítás alatt',delivered:'Kézbesítve',failed:'Sikertelen kézbesítés',returned:'Visszaküldve'},fulfilment:{not_ready:'Nincs összekészítve',picking:'Összekészítés alatt',ready_to_deliver:'Szállításra kész',handed_over:'Átadva a futárnak'},invoice:{not_started:'Nincs számlázva',pending:'Számlázás folyamatban',invoiced:'Számlázva',failed:'Számlázási hiba',storno:'Sztornózva'},order:{created:'Létrehozva',bought:'Megvásárolva',cancelled:'Törölve',refunded:'Visszatérítve'}},
  systemMessages:{checkoutPaused:'A rendelésfelvétel átmenetileg szünetel.',loginRequired:'A rendeléshez bejelentkezés szükséges.',accessPending:'Az alkalmazás-hozzáférés nincs jóváhagyva.',invalidOrder:'Érvénytelen rendelési adatok.',requiredCustomerFields:'Név, érvényes e-mail és szállítási cím szükséges.',cartEmpty:'A kosár üres.',unavailable:'A termék jelenleg nem rendelhető.',orderSaved:'Rendelés mentve.',orderAcceptedDemo:'Rendelés fogadva demó módban; MongoDB nincs konfigurálva.'},
  seo:{siteTitle:'deli.africa — Dél-Afrika, válogatva',siteDescription:'Kurált dél-afrikai ízek: peri-peri, chutney, rooibos, braai fűszerek és klasszikus snackek.',productTitleTemplate:'{name} – dél-afrikai háttér, íz és felhasználás'}
};

export const DEFAULT_STOREFRONT_UI_COPY = merge(DEFAULT_UI_COPY, STOREFRONT_COPY_EXTENSION);
export function applyTemplate(template, values = {}) { return String(template || '').replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key) => values[key] ?? ''); }
