'use client';

import { useEffect, useState } from 'react';

const specs = {
  packeta: { title:'Packeta', secrets:[['apiKey','API key'],['apiPassword','API password']], public:[['senderId','Sender ID'],['country','Country'],['language','Language']] },
  barion: { title:'Barion', secrets:[['posKey','POS key']], public:[['payee','Payee e-mail'],['currency','Currency']] },
  billingo: { title:'Billingo', secrets:[['apiKey','API key']], public:[['blockId','Document block ID'],['bankAccountId','Bank account ID']] }
};

export default function IntegrationsClient(){
  const [data,setData]=useState({}); const [drafts,setDrafts]=useState({}); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  async function load(){const r=await fetch('/api/admin/integrations',{cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'Integrációk nem tölthetők be.');return;}setData(j.integrations||{});setDrafts(Object.fromEntries(Object.entries(j.integrations||{}).map(([k,v])=>[k,{enabled:v.enabled,credentials:{},publicConfig:v.publicConfig||{},clearFields:[]}])));}
  useEffect(()=>{load();},[]);
  function setField(provider,group,field,value){setDrafts(d=>({...d,[provider]:{...d[provider],[group]:{...(d[provider]?.[group]||{}),[field]:value}}}));}
  function toggleClear(provider,field,checked){setDrafts(d=>({...d,[provider]:{...d[provider],clearFields:checked?[...(d[provider]?.clearFields||[]),field]:(d[provider]?.clearFields||[]).filter(v=>v!==field)}}));}
  async function save(provider){setMessage('');setError('');const payload={provider,...drafts[provider]};const r=await fetch('/api/admin/integrations',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setError(j.error||'Mentési hiba.');return;}setMessage(`${specs[provider].title} mentve.`);await load();}
  return <><div className="admin-page-head"><div><span className="admin-kicker">THIRD-PARTY SERVICES</span><h1>Integrációk</h1><p>A szolgáltatói kulcsok itt állíthatók be. A titkos értékek titkosítva kerülnek MongoDB-be és visszaolvasáskor nem jelennek meg.</p></div></div>{message&&<div className="admin-message">{message}</div>}{error&&<div className="admin-error">{error}</div>}<div className="integration-grid">{Object.entries(specs).map(([provider,spec])=>{const state=data[provider]||{};const draft=drafts[provider]||{credentials:{},publicConfig:{},clearFields:[]};return <section className="integration-card" key={provider}><h2>{spec.title}</h2><p><span className={`status-pill ${draft.enabled?'ok':'warn'}`}>{draft.enabled?'Enabled':'Disabled'}</span></p><label><input type="checkbox" checked={Boolean(draft.enabled)} onChange={e=>setDrafts(d=>({...d,[provider]:{...d[provider],enabled:e.target.checked}}))}/> Integráció engedélyezve</label><h3>Titkos kulcsok</h3>{spec.secrets.map(([field,label])=><div key={field} style={{marginBottom:12}}><label>{label}<input style={{width:'100%',padding:10}} type="password" placeholder={state.configuredFields?.[field]?'Beállítva — hagyd üresen a megtartáshoz':'Nincs beállítva'} value={draft.credentials?.[field]||''} onChange={e=>setField(provider,'credentials',field,e.target.value)}/></label>{state.configuredFields?.[field]&&<label style={{fontSize:11}}><input type="checkbox" checked={(draft.clearFields||[]).includes(field)} onChange={e=>toggleClear(provider,field,e.target.checked)}/> meglévő kulcs törlése</label>}</div>)}<h3>Nyilvános konfiguráció</h3>{spec.public.map(([field,label])=><label key={field} style={{display:'block',marginBottom:10}}>{label}<input style={{width:'100%',padding:10}} value={draft.publicConfig?.[field]||''} onChange={e=>setField(provider,'publicConfig',field,e.target.value)}/></label>)}<button className="admin-button red" onClick={()=>save(provider)}>{spec.title} mentése</button></section>})}</div><section className="admin-panel"><h2>Biztonság</h2><p>A credential mezők nem kerülnek vissza a böngészőbe. A titkosításhoz a <code>SETTINGS_ENCRYPTION_KEY</code> környezeti változó ajánlott; ha nincs, az alkalmazás a meglévő SSO kliens titkát használja kulcsszármaztatáshoz.</p></section></>;
}
