'use client';

import { useEffect, useState } from 'react';

export default function StorefrontClient(){
  const [heroMode,setHeroMode]=useState('fixed');
  const [categorySelectorMode,setCategorySelectorMode]=useState('fixed');
  const [sales,setSales]=useState({checkoutEnabled:true,senderName:'deli.africa',supportEmail:'',termsUrl:'/legal/gtc',privacyUrl:'/legal/privacy'});
  const [message,setMessage]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/site-settings',{cache:'no-store'}).then(r=>r.json()).then(d=>{setHeroMode(d.heroMode||'fixed');setCategorySelectorMode(d.categorySelectorMode||'fixed');setSales(s=>({...s,...(d.sales||{})}));}).catch(()=>setError('A beállítások nem tölthetők be.'));},[]);
  async function save(){setMessage('');setError('');const r=await fetch('/api/site-settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({heroMode,categorySelectorMode,sales})});const d=await r.json();if(!r.ok){setError(d.error||'Mentési hiba.');return;}setMessage('Megjelenés és rendelési beállítások mentve.');}
  return <><div className="admin-page-head"><div><span className="admin-kicker">STOREFRONT SETTINGS</span><h1>Megjelenés és checkout</h1><p>Hero, kategóriakártyák és a rendelésfelvétel alapbeállításai.</p></div><button className="admin-button red" onClick={save}>Mentés</button></div>{message&&<div className="admin-message">{message}</div>}{error&&<div className="admin-error">{error}</div>}<section className="admin-panel"><h2>Hero megjelenés</h2><div className="admin-form-grid"><label>Hero mód<select value={heroMode} onChange={e=>setHeroMode(e.target.value)}><option value="fixed">Fix kliensfotók</option><option value="interactive">Interaktív termékkompozíció</option></select></label><label>Kategóriaválasztó<select value={categorySelectorMode} onChange={e=>setCategorySelectorMode(e.target.value)}><option value="fixed">Fix fotómontázs</option><option value="generated">Generált kártya</option></select></label></div></section><section className="admin-panel"><h2>Rendelési alapbeállítások</h2><div className="admin-form-grid"><label><input type="checkbox" checked={sales.checkoutEnabled!==false} onChange={e=>setSales(s=>({...s,checkoutEnabled:e.target.checked}))}/> Rendelésfelvétel engedélyezve</label><label>Feladó neve<input value={sales.senderName||''} onChange={e=>setSales(s=>({...s,senderName:e.target.value}))}/></label><label>Ügyfélszolgálati e-mail<input value={sales.supportEmail||''} onChange={e=>setSales(s=>({...s,supportEmail:e.target.value}))}/></label><label>ÁSZF URL<input value={sales.termsUrl||''} onChange={e=>setSales(s=>({...s,termsUrl:e.target.value}))}/></label><label>Adatkezelési URL<input value={sales.privacyUrl||''} onChange={e=>setSales(s=>({...s,privacyUrl:e.target.value}))}/></label></div></section></>;
}
