'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import BrandLogo from '@/app/components/BrandLogo';
import { APP_VERSION } from '@/lib/version';
import { DEFAULT_SALES_SETTINGS, DEFAULT_STOREFRONT_CONTENT } from '@/lib/site-config';

const money = (value) => new Intl.NumberFormat('hu-HU').format(value || 0) + ' Ft';
const uptime = (seconds) => seconds == null ? '…' : `${Math.floor(seconds / 60)} perc`;

export default function DashboardClient({ user }) {
  const [health, setHealth] = useState(null);
  const [error, setError] = useState('');
  const [dimensions, setDimensions] = useState([]);
  const [saveState, setSaveState] = useState('');
  const [heroMode, setHeroMode] = useState('fixed');
  const [categorySelectorMode, setCategorySelectorMode] = useState('fixed');
  const [content, setContent] = useState(DEFAULT_STOREFRONT_CONTENT);
  const [sales, setSales] = useState(DEFAULT_SALES_SETTINGS);
  const [providerReadiness, setProviderReadiness] = useState({ packeta: false, barion: false, billingo: false });
  const [heroSaveState, setHeroSaveState] = useState('');
  const [contentSaveState, setContentSaveState] = useState('');
  const [salesSaveState, setSalesSaveState] = useState('');
  async function refresh() {
    try { const res = await fetch('/api/health', { cache: 'no-store' }); if (!res.ok) throw new Error('Health endpoint failed'); setHealth(await res.json()); setError(''); }
    catch (e) { setError(e instanceof Error ? e.message : 'Health endpoint failed'); }
  }
  useEffect(() => { refresh(); const id = setInterval(refresh, 15000); return () => clearInterval(id); }, []);
  useEffect(() => { fetch('/api/product-settings', { cache: 'no-store' }).then((res) => res.json()).then((data) => setDimensions(data.products || [])).catch(() => setError('A termékméretek nem tölthetők be.')); }, []);
  useEffect(() => { fetch('/api/site-settings', { cache: 'no-store' }).then((res) => res.json()).then((data) => {
    setHeroMode(data.heroMode || 'fixed'); setCategorySelectorMode(data.categorySelectorMode || 'fixed');
    setContent({ ...DEFAULT_STOREFRONT_CONTENT, ...(data.storefrontContent || {}) }); setSales({ ...DEFAULT_SALES_SETTINGS, ...(data.sales || {}) });
    setProviderReadiness(data.providerReadiness || { packeta: false, barion: false, billingo: false });
  }).catch(() => setError('A webshop beállításai nem tölthetők be.')); }, []);
  function changeDimension(id, field, value) { setDimensions((current) => current.map((item) => item.id === id ? { ...item, [field]: value } : item)); }
  async function saveDimension(item) {
    setSaveState(item.id);
    const res = await fetch('/api/product-settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ productId: item.id, width: Number(item.width), height: Number(item.height) }) });
    setSaveState(res.ok ? `saved:${item.id}` : `error:${item.id}`);
  }
  async function saveHeroMode(event) {
    event.preventDefault();
    setHeroSaveState('saving');
    const res = await fetch('/api/site-settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ heroMode, categorySelectorMode }) });
    setHeroSaveState(res.ok ? 'saved' : 'error');
  }
  async function saveSettings(event, key, value, setter) { event.preventDefault(); setter('saving'); const res = await fetch('/api/site-settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ [key]: value }) }); setter(res.ok ? 'saved' : 'error'); }
  function updateContent(key, value) { setContent((current) => ({ ...current, [key]: value })); }
  function updateSales(key, value) { setSales((current) => ({ ...current, [key]: value })); }
  const mongoOk = health?.mongo?.connected;
  return <main className="dashboard-shell">
    <div className="dashboard-top"><Link href="/" className="brand-link"><BrandLogo /></Link><div className="admin-account"><span>{user.name}<small>{user.email}</small></span><a className="button button-dark" href="/api/auth/logout">Kijelentkezés</a><button onClick={refresh} className="button button-red">Frissítés</button></div></div>
    <div className="dashboard-title"><span>ADMIN SETTINGS · GENERAL DASHBOARD · v{APP_VERSION}</span><h1>Élő rendszerállapot</h1><p>15 másodpercenként frissülő, SSO-védett produkciós áttekintés.</p>{health && <small>Utolsó mérés: {new Date(health.timestamp).toLocaleString('hu-HU')}</small>}</div>
    {error && <div className="alert">{error}</div>}
    <section className="metric-grid">
      <article className="metric"><span className={`status-dot ${mongoOk ? 'ok' : 'warn'}`} /><small>MongoDB</small><strong>{health ? health.mongo.state : 'Ellenőrzés…'}</strong><p>{health?.mongo?.configured === false ? 'A MongoDB-kapcsolati változó nincs beállítva.' : 'Adatbázis-kapcsolat állapota.'}</p></article>
      <article className="metric"><span className={`status-dot ${health?.authentication?.configured ? 'ok' : 'warn'}`} /><small>SSO</small><strong>{health?.authentication?.configured ? 'Configured' : 'Missing config'}</strong><p>{health?.authentication?.provider || 'DoneIsBetter SSO'} · admin session</p></article>
      <article className="metric"><small>Környezet</small><strong>{health?.environment || '…'}</strong><p>{health?.runtime || '…'} · {health?.deployment?.region || '…'}</p></article>
      <article className="metric"><small>Health latency</small><strong>{health ? `${health.latencyMs} ms` : '…'}</strong><p>API válaszidő az utolsó ellenőrzésnél.</p></article>
      <article className="metric"><small>Összes rendelés</small><strong>{health?.orders?.available ? health.orders.total : 'N/A'}</strong><p>Ma: {health?.orders?.available ? health.orders.today : 'N/A'}</p></article>
      <article className="metric"><small>Nyitott rendelések</small><strong>{health?.orders?.available ? health.orders.open : 'N/A'}</strong><p>Új vagy visszaigazolt állapot.</p></article>
      <article className="metric"><small>Rendelési érték</small><strong>{health?.orders?.available ? money(health.orders.revenue) : 'N/A'}</strong><p>Nem törölt rendelések összesen.</p></article>
      <article className="metric"><small>Folyamat</small><strong>{uptime(health?.process?.uptimeSeconds)}</strong><p>{health?.process?.memoryMb || '…'} MB memória · {health?.process?.node || '…'}</p></article>
    </section>
    <section className="dashboard-panel"><h2>Szolgáltatások és kiadás</h2><div className="service-row"><span>Storefront</span><b>Online</b></div><div className="service-row"><span>Orders API</span><b>SSO protected</b></div><div className="service-row"><span>Detailed health API</span><b>Admin only</b></div><div className="service-row"><span>Socket.io endpoint</span><b>{health?.realtime?.status === 'endpoint-ready' ? 'Ready' : 'Checking'}</b></div><div className="service-row"><span>MongoDB persistence</span><b>{mongoOk ? 'Connected' : 'Unavailable'}</b></div><div className="service-row"><span>Admin identity</span><b>{health?.authentication?.admin?.email || user.email}</b></div><div className="service-row"><span>Release</span><b>v{health?.deployment?.version || APP_VERSION} · {health?.deployment?.commit || '…'}</b></div><div className="service-row"><span>Production URL</span><b>{health?.deployment?.url || '…'}</b></div></section>
    <form className="hero-setting-panel" onSubmit={saveHeroMode}><div><span>STOREFRONT DISPLAY</span><h2>Vizuális megjelenés</h2><p>A hero választás a nyitó- és kategóriaoldalakat vezérli. A termékoldalak mindig a pontos termékfotót használják.</p></div><h3>Hero</h3><div className="hero-mode-options"><label className={heroMode === 'fixed' ? 'active' : ''}><input type="radio" name="heroMode" value="fixed" checked={heroMode === 'fixed'} onChange={(event) => setHeroMode(event.target.value)} /><b>Fix kliensfotók</b><small>A mellékelt kész kompozíciók.</small></label><label className={heroMode === 'interactive' ? 'active' : ''}><input type="radio" name="heroMode" value="interactive" checked={heroMode === 'interactive'} onChange={(event) => setHeroMode(event.target.value)} /><b>Generált interaktív</b><small>Környezet és külön termék-elhelyezés.</small></label></div><h3>Kategóriaválasztó a főoldalon</h3><div className="hero-mode-options"><label className={categorySelectorMode === 'fixed' ? 'active' : ''}><input type="radio" name="categorySelectorMode" value="fixed" checked={categorySelectorMode === 'fixed'} onChange={(event) => setCategorySelectorMode(event.target.value)} /><b>Fix fotómontázs</b><small>A kész kategóriafotó háttérként, bal felső szöveggel.</small></label><label className={categorySelectorMode === 'generated' ? 'active' : ''}><input type="radio" name="categorySelectorMode" value="generated" checked={categorySelectorMode === 'generated'} onChange={(event) => setCategorySelectorMode(event.target.value)} /><b>Generált kártya</b><small>Egyszínű háttér és külön termékkép.</small></label></div><button className="button button-red" disabled={heroSaveState === 'saving'}>{heroSaveState === 'saving' ? 'Mentés…' : heroSaveState === 'saved' ? 'Mentve ✓' : 'Megjelenés mentése'}</button>{heroSaveState === 'error' && <p className="form-error">A megjelenés mentése sikertelen.</p>}</form>
    <form className="settings-panel" onSubmit={(event) => saveSettings(event, 'storefrontContent', content, setContentSaveState)}><div><span>EDITABLE CONTENT</span><h2>Főoldali szövegek</h2><p>A hero, történet és „Miért mi?” blokk szövegei innen módosíthatók.</p></div><div className="settings-fields"><label>Hero felső cím<input value={content.heroEyebrow} onChange={(event) => updateContent('heroEyebrow', event.target.value)} /></label><label>Hero főcím<textarea value={content.heroTitle} onChange={(event) => updateContent('heroTitle', event.target.value)} /></label><label className="wide">Hero leírás<textarea value={content.heroBody} onChange={(event) => updateContent('heroBody', event.target.value)} /></label><label>Hero gomb<input value={content.heroButton} onChange={(event) => updateContent('heroButton', event.target.value)} /></label><label>Történet címke<input value={content.storyLabel} onChange={(event) => updateContent('storyLabel', event.target.value)} /></label><label className="wide">Történet címe<input value={content.storyTitle} onChange={(event) => updateContent('storyTitle', event.target.value)} /></label><label className="wide">Történet szövege<textarea rows="6" value={content.storyBody} onChange={(event) => updateContent('storyBody', event.target.value)} /></label><label>Miért mi? címke<input value={content.whyLabel} onChange={(event) => updateContent('whyLabel', event.target.value)} /></label><label>Miért mi? cím<textarea value={content.whyTitle} onChange={(event) => updateContent('whyTitle', event.target.value)} /></label><label className="wide">Miért mi? leírás<textarea value={content.whyBody} onChange={(event) => updateContent('whyBody', event.target.value)} /></label></div><button className="button button-red" disabled={contentSaveState === 'saving'}>{contentSaveState === 'saving' ? 'Mentés…' : contentSaveState === 'saved' ? 'Mentve ✓' : 'Szövegek mentése'}</button>{contentSaveState === 'error' && <p className="form-error">A szövegek mentése sikertelen.</p>}</form>
    <form className="settings-panel" onSubmit={(event) => saveSettings(event, 'sales', sales, setSalesSaveState)}><div><span>SALES PROCESS PREPARATION</span><h2>Rendelési folyamat</h2><p>A célfolyamat: Packeta automata → Barion fizetés → Billingo számla. A kapcsolatok csak a szolgáltatói kulcsok megadása után aktiválhatók.</p></div><div className="readiness-grid"><article className={providerReadiness.packeta ? 'ready' : 'missing'}><b>Packeta</b><span>{providerReadiness.packeta ? 'Kulcs beállítva' : 'API-kulcs szükséges'}</span></article><article className={providerReadiness.barion ? 'ready' : 'missing'}><b>Barion</b><span>{providerReadiness.barion ? 'POS-kulcs beállítva' : 'POS-kulcs szükséges'}</span></article><article className={providerReadiness.billingo ? 'ready' : 'missing'}><b>Billingo</b><span>{providerReadiness.billingo ? 'Kulcs beállítva' : 'API-kulcs szükséges'}</span></article></div><div className="settings-fields"><label className="toggle wide"><input type="checkbox" checked={sales.checkoutEnabled} onChange={(event) => updateSales('checkoutEnabled', event.target.checked)} />Rendelésfelvétel engedélyezve</label><label>Átvétel<input value="Packeta csomagautomata" disabled /></label><label>Fizetés<input value="Barion" disabled /></label><label>Számlázás<input value="Billingo" disabled /></label><label>Feladó neve<input value={sales.senderName} onChange={(event) => updateSales('senderName', event.target.value)} /></label><label>Ügyfélszolgálati e-mail<input type="email" value={sales.supportEmail} onChange={(event) => updateSales('supportEmail', event.target.value)} /></label><label>ÁSZF URL<input type="url" value={sales.termsUrl} onChange={(event) => updateSales('termsUrl', event.target.value)} /></label><label>Adatkezelési URL<input type="url" value={sales.privacyUrl} onChange={(event) => updateSales('privacyUrl', event.target.value)} /></label></div><button className="button button-red" disabled={salesSaveState === 'saving'}>{salesSaveState === 'saving' ? 'Mentés…' : salesSaveState === 'saved' ? 'Mentve ✓' : 'Rendelési beállítások mentése'}</button>{salesSaveState === 'error' && <p className="form-error">A rendelési beállítások mentése sikertelen.</p>}</form>
    <section className="settings-panel"><div><span>V1.0 ADMIN AUDIT</span><h2>Lefedettség és hiányzó erőforrások</h2></div><div className="audit-list"><div><b>Kész</b><span>Hivatalos logók, hero- és kategóriaváltó, szerkeszthető főoldali szövegek, 1:1 termékfotók, termékoldal-linkek, kosár és rendelésmentés.</span></div><div><b>Előkészítve</b><span>Packeta, Barion és Billingo célfolyamat, szolgáltatói állapotjelzés és jogi URL-ek.</span></div><div><b>Kapcsolásra vár</b><span>Packeta API-kulcs, Barion POS-kulcs, Billingo API-kulcs, végleges ÁSZF és adatkezelési oldalak.</span></div><div><b>Roadmap</b><span>Profil/rendeléstörténet és pontok, csomagoldalak, admin fájlfeltöltés, teljes oldalas Packeta–Barion checkout.</span></div></div></section>
    <section className="dimension-panel"><div><span>PRODUCT DISPLAY SETTINGS</span><h2>Valós termékméretek</h2><p>Add meg a csomagolás szélességét és magasságát milliméterben. A hero ezeket az arányokat használja.</p></div><div className="dimension-list">{dimensions.map((item) => <form key={item.id} onSubmit={(event) => { event.preventDefault(); saveDimension(item); }}><b>{item.name}</b><label>Szélesség (mm)<input type="number" min="1" max="2000" step="1" value={item.width} onChange={(event) => changeDimension(item.id, 'width', event.target.value)} /></label><label>Magasság (mm)<input type="number" min="1" max="2000" step="1" value={item.height} onChange={(event) => changeDimension(item.id, 'height', event.target.value)} /></label><button className="button button-red" disabled={saveState === item.id}>{saveState === item.id ? 'Mentés…' : saveState === `saved:${item.id}` ? 'Mentve ✓' : 'Mentés'}</button></form>)}</div></section>
  </main>;
}
